### ISSUE TITLE
Latest version spams chat...

### ISSUE THREAD

**Issue by XanderCodes** [TH3AL3X/uEssentials#1]
What is this lol
![image](https://user-images.githubusercontent.com/19631080/113975183-7c173c00-9882-11eb-9cef-bce763aabd32.png)

**Comment by XanderCodes** [comment]
Looks like I jumped the gun a little bit... there may be an issue loading older uEssentials configs with the latest versions of your fork.

When they fail to load, the plugin reverts to default configuration, enabling AutoAnnouncer, but hides the fact it's enabled from the end user, as all they see is the old config file. - Just a hypothesis 

Also `/essentials reload` is broken - back to server restarts.

**Comment by TeemoCell** [comment]
`/rocket reload uEssentials` is working fine for me.

**Comment by TH3AL3X** [comment]
> What is this lol
> ![image](https://user-images.githubusercontent.com/19631080/113975183-7c173c00-9882-11eb-9cef-bce763aabd32.png)

You need to disable autoannouncements in the config.json

**Comment by TH3AL3X** [comment]
> Looks like I jumped the gun a little bit... there may be an issue loading older uEssentials configs with the latest versions of your fork.
> 
> When they fail to load, the plugin reverts to default configuration, enabling AutoAnnouncer, but hides the fact it's enabled from the end user, as all they see is the old config file. - Just a hypothesis
> 
> Also `/essentials reload` is broken - back to server restarts.

Aight, you need to remove the old  uEssentials folder, and let generate a new one
