### ISSUE TITLE
Problem to give XP

### ISSUE THREAD

**Issue by Gedehamsen021** [TH3AL3X/uEssentials#10]
the xp just send to player when he kill a zombie or player or cut a tree

**Comment by Gedehamsen021** [comment]
in the case problem with Kit given

**Comment by TH3AL3X** [comment]
Mmm, can you explain better what is going on?

**Comment by TH3AL3X** [comment]
Record it if you can

**Comment by Gedehamsen021** [comment]
when i execute the command
https://gyazo.com/eeca30ec0a201cf305c546256676c60f

before kill or cut a tree
https://gyazo.com/eeca30ec0a201cf305c546256676c60f

**Comment by TH3AL3X** [comment]
Gotta check that

**Comment by TH3AL3X** [comment]
I think it is an unturned problem

**Comment by TH3AL3X** [comment]
I already fixed it, ty for the report

**Comment by kulkaGM** [comment]
Yea you fixed it in /experience command, but forget to do same thing in Kits. #15
