### ISSUE TITLE
Can't unban someone when banned with /slay, animals spawned with /animals keep resoawning after they die

### ISSUE THREAD

**Issue by WFPhantom** [TH3AL3X/uEssentials#14]
When you /slay someone, /unban <steam64id> doesnt unban them for some reason, but gives no output in logs (hence why I havent included them). Same with /animal. You spawn an animal then kill it, but it just respawns where you spawned it originally, Could you please look into it?

**Comment by TH3AL3X** [comment]
The animal thing is normal, i think it's impossible to do it in other way, is getting all positions of the dead animals, you can check the code, but it's the only way...

**Comment by TH3AL3X** [comment]
And the unban and slay thing, it's probably that you have the rocketmod outdated, anyways I will check it tomorrow, I gotta sleep
