### ISSUE TITLE
Death Message

### ISSUE THREAD

**Issue by TeemoCell** [TH3AL3X/uEssentials#2]
Getting that error, every time someone dies.
https://paste.mod.gg/zojuqipego.css

**I would also like to thank you for your work and the updates.**

**Comment by TH3AL3X** [comment]
gotta check that, sorry for the delay

**Comment by TeemoCell** [comment]
Hey, any news?

**Comment by TH3AL3X** [comment]
> Hey, any news?

Ya, i'm very busy gotta check that, sorry for the delay

**Comment by TH3AL3X** [comment]
Should be fixed now @TeemoCell
