### ISSUE TITLE
command bug

### ISSUE THREAD

**Issue by Blackwolf7704** [TH3AL3X/uEssentials#21]
After the unturned new update (3.21.31.0), home and tpa bugs have occurred.

The home command does not get the correct position,
The same goes for tpa. Also, the tp command has had a phenomenon where tp was not possible for the target in the vehicle before, is it possible to update it?

**Comment by TeemoCell** [comment]
Everything works fine for me. Are you **uEssentials** homes or **MoreHomes**?

**Comment by Blackwolf7704** [comment]
I use uEssentials homes

**Comment by TH3AL3X** [comment]
Nelson made an update 5 months ago to prevent glitching with teleports, this implemented in uEssentials as legacy deleting the above, he could put in the configuration a Standard and Legacy mode for those who want the old teleport

>

**Comment by Blackwolf7704** [comment]
how can i do it?

**Comment by TH3AL3X** [comment]
> how can i do it? I don't know change standard and lagacy mode...
> 
> Also, there's something I didn't understand.
> 
> 1. Are you saying that Essentials was made in legacy mode, and that the flaws were fixed?
> 2. Is it possible to teleport to a person in a vehicle using standard mode?
> 
> If number 2 is possible, can you tell me how to change to standard mode?

I have another idea, something that can detect when someone is in a vehicle, and automatically change it to legacy teleport, that the best way, i will do an update to night

**Comment by TH3AL3X** [comment]
> how can i do it? I don't know change standard and lagacy mode...
> 
> Also, there's something I didn't understand.
> 
> 1. Are you saying that Essentials was made in legacy mode, and that the flaws were fixed?
> 2. Is it possible to teleport to a person in a vehicle using standard mode?
> 
> If number 2 is possible, can you tell me how to change to standard mode?

Try this version
https://github.com/TH3AL3X/uEssentials/releases/download/1.3.7.5/uEssentials.dll
