### ISSUE TITLE
Plugin causing high ping lag and lag spikes in players, unloading plugin reduces ping to stable level

### ISSUE THREAD

**Issue by CheeseLad** [TH3AL3X/uEssentials#23]
Hi,

Not sure if this can be solved as it may be due to the nature of the plugin, but recently I found out that this plugin is causing high ping lag in players and causes lag spikes to occur. I discovered this when trying to diagnose the issue, I found that if I unloaded the uEssentials plugin, waited around 2 mins, then loaded it again, the lag would disappear, it would come back in maybe 8-10 hours but it was a good fix. I was wondering if it would be possible to get this fixed? I can provide more info about my server if needed.

Thanks :)

**Comment by TH3AL3X** [comment]
Mmmm, idk what is causing it, I will check what is going on, but for me I'm not getting any lag spikes

**Comment by TH3AL3X** [comment]
Can you send me your config.json, want to see what do you have enabled

**Comment by CheeseLad** [comment]
Yes I can
