### ISSUE TITLE
Antispam in server's logs?

### ISSUE THREAD

**Issue by SSGamingServers** [TH3AL3X/uEssentials#24]
I get this from server spaming in logs an issue
I think this is causing lag and crashes maybe
uEssentials >> Antispam is active; wait to chat again.
Unturned.exe Error: 0 : [uEssentials] [DEBUG] Authentication to host '127.0.0.1' for user 'Username' using method 'mysql
_native_password' failed with message: Access denied for user 'Username'@'localhost' (using password: YES)

**Comment by TH3AL3X** [comment]
Can you send me your rocket logs please?

**Comment by TH3AL3X** [comment]
It's a problem of your MySql
