### ISSUE TITLE
 It's not a problem, it's a request

### ISSUE THREAD

**Issue by MalevichFX** [TH3AL3X/uEssentials#27]
_Prevent players from building at loot spawns!_

**Add in config.json**

`"Allow_Placing_On_Vehicles": false or true`
`"Allow_Structures": false or true`
`"Allow_Barricades": false or true`
**Please!**

**Comment by TH3AL3X** [comment]
> _Prevent players from building at loot spawns!_
> 
> **Add in config.json**
> 
> `"Allow_Placing_On_Vehicles": false or true` `"Allow_Structures": false or true` `"Allow_Barricades": false or true` **Please!**

I will check that

**Comment by MalevichFX** [comment]
> > _Не позволяйте игрокам строить в местах появления добычи!_
> > **Добавьте в config.json**
> > `"Allow_Placing_On_Vehicles": false or true` `"Allow_Structures": false or true` `"Allow_Barricades": false or true` **Пожалуйста!**
> 
> я проверю это

Спасибо буду очень благодарен/Thank you I will be very grateful

**Comment by TH3AL3X** [comment]
> > > _Prevent players from building at loot spawns!_
> > > **Add in config.json**
> > > `"Allow_Placing_On_Vehicles": false or true` `"Allow_Structures": false or true` `"Allow_Barricades": false or true` **Please!**
> > 
> > 
> > I will check that
> 
> Thank you, I will be very grateful!

In the unturned config.json, you can disable the vehicle structures build
"Barricades": {
      "Decay_Time": 604800,
      "Armor_Lowtier_Multiplier": 1.0,
      "Armor_Hightier_Multiplier": 0.5,
      "Gun_Lowcal_Damage_Multiplier": 1.0,
      "Gun_Highcal_Damage_Multiplier": 1.0,
      "Melee_Damage_Multiplier": 1.0,
      **"Allow_Item_Placement_On_Vehicle": true,
      "Allow_Trap_Placement_On_Vehicle": true,**
      "Max_Item_Distance_From_Hull": 64.0,
      "Max_Trap_Distance_From_Hull": 16.0
    },

Anyways i'm doing the build prevention in loot zones

**Comment by TH3AL3X** [comment]
Done, you need to delete your config.json, now people can't build in buildings
https://github.com/TH3AL3X/uEssentials/releases/tag/1.3.7.8

**Comment by MalevichFX** [comment]
> Готово, вам нужно удалить свой config.json, теперь люди не могут строить в зданиях https://github.com/TH3AL3X/uEssentials/releases/tag/1.3.7.8

Thank you very much, you helped me a lot!
