### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by MalevichFX** [TH3AL3X/uEssentials#28]
Hey And yes, remove this, when a player enters the server for him, it says that the server uses this plugin and version

**Comment by TH3AL3X** [comment]
Disable this function on uEssentials config.json
**AlertOnJoin: false**

**Comment by MalevichFX** [comment]
> Отключить эту функцию в uEssentials config.json **AlertOnJoin: false**

It did not help anyway writes in the chat that the project uses this plugin and yogo version

**Comment by TH3AL3X** [comment]
> > Отключить эту функцию в uEssentials config.json **AlertOnJoin: false**
> 
> 
> 
> It did not help anyway writes in the chat that the project uses this plugin and yogo version
> 
> 

I will check that, and the shutdown too, I'm busy right now

**Comment by MalevichFX** [comment]
> > > Отключить эту функцию в uEssentials config.json **AlertOnJoin: false**
> > 
> > 
> > It did not help anyway writes in the chat that the project uses this plugin and yogo version
> 
> I will check that, and the shutdown too, I'm busy right now

Thank you in advance, thank you very good man, good luck to you)

**Comment by TH3AL3X** [comment]
I removed the alertonjoin, and fixed some stuff, now i will check the shutdown thing, because i don't know how they did this part of code
