### ISSUE TITLE
Constant Spamming Text

### ISSUE THREAD

**Issue by cppchrp** [TH3AL3X/uEssentials#31]
The whole thing works completely fine but it spams in the chat "This is an announcement" and "This is something" but this doesn't stop and I don't know any code or anything so I have no idea how to fix this spamming

**Comment by TH3AL3X** [comment]
Config.json, you have the autoannouncement

**Comment by cppchrp** [comment]
> Config.json, you have the autoannouncement

Should I delete Config.json? Because I have found it

**Comment by cppchrp** [comment]
Wait nvm I went into it and removed the messages, Thanks
