### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by cutetamz** [TH3AL3X/uEssentials#32]
Hey! I was trying to use poll, but i couldn't understand how it works
i tried this

```
[World] tamz [cutetamz]: "/poll start name 60 desc"
[uEssentials] [ERROR] An error ocurred while executing command: 'poll start name 60 desc'
[uEssentials] [ERROR] Value cannot be null.
Parameter name: key
```
which part is wrong?

**Comment by TH3AL3X** [comment]
I really don't know how to use that, I need to check into the code, I'm busy those days, I will take a look soon

**Comment by TH3AL3X** [comment]
Hello again, sorry for taking so long, i already fixed it in the last version
https://github.com/TH3AL3X/uEssentials/releases/tag/1.3.8.1
