### ISSUE TITLE
Death Messages are broken + Double join messages.

### ISSUE THREAD

**Issue by gamer1117** [TH3AL3X/uEssentials#35]
When a player joins the server it will display the join message twice. Also death messages are just as broken as they are in the original repo however this one claims to fix them.

**Comment by TH3AL3X** [comment]
> 

I will check what is going on, can you send me your rocket logs, so i can check what is the problem?

**Comment by gamer1117** [comment]
Hi Alex. I found the issue here was that 2 uEssentials.dll files were being loaded, first your fork and secondly the latest master. I had renamed the master .dll to"uEssentials - backup" and didn't realize it was still being loaded. When a player joined 2 join messages were broadcast because 2 uEssentials plugins were loaded, death messages didnt work because of this issue as well.

So I've just removed the master .dll and I find that you're most recent release works great. Does everything it says it should.

**Comment by TH3AL3X** [comment]
Alright
