### ISSUE TITLE
Kits clearing when stopping server, while booting up

### ISSUE THREAD

**Issue by realtrollman2319** [TH3AL3X/uEssentials#36]
how to reproduce
Stop server
Once you see mounting core, stop server

**Comment by TH3AL3X** [comment]
Sorry for this problem, I will try to fix it as soon as possible, I thought it was already solved

**Comment by TH3AL3X** [comment]
Pd, are you sure you have the latest version of the plugin?

**Comment by TeemoCell** [comment]
I guess he use a old version. Never had that problem since i use this version.

**Comment by TH3AL3X** [comment]
Because you have not responded, I will proceed to close this
