### ISSUE TITLE
/vote command conflicts with the plugin: "VoteRewards"

### ISSUE THREAD

**Issue by realtrollman2319** [TH3AL3X/uEssentials#37]
It's making it unusuable if you have VoteRewards on your server.
How to fix?
Change /vote into /pollvote.

**Comment by TH3AL3X** [comment]
In the server, you have a file for disable commands of plugins and you can change the name by your self too

**Comment by realtrollman2319** [comment]
I want both commands at the same time.

**Comment by TH3AL3X** [comment]
I will change the command to votepoll, but it is also possible that you change it in the config outside the plugins folder

**Comment by realtrollman2319** [comment]
Talking about the kits, it still breaks, and yes i'm at the latest release
