### ISSUE TITLE
uEssentials kits breaking when doing a wrong parse in JSON, also when restarting server

### ISSUE THREAD

**Issue by realtrollman2319** [TH3AL3X/uEssentials#39]
Yes i'm at the latest release.
I've had problems with this and it's sooo annoying, so here is how to reproduce it:
Open up the server
When you see the line "[loading] uEssentials" and beyond, stop the server.

Another method of reproduce:
Do a wrong parse in JSON. Delete a comma

**Comment by TH3AL3X** [comment]
uEssentials could be that it is eliminating its kits.json because there is some lack of format in el suyo

**Comment by TH3AL3X** [comment]
uEssentials may be eliminating your kits.json because there is some format failure in your kits.json

**Comment by realtrollman2319** [comment]
But when I don't make a wrong format, it just removes it on the random times of booting server.

> uEssentials may be eliminating your kits.json because there is some format failure in your kits.json

**Comment by realtrollman2319** [comment]
I suggest making a kits backup for the plugin.

**Comment by TH3AL3X** [comment]
I'm checking the code, let me see whats happening, if you can, send me your kits.json and your rocket.log here

**Comment by TH3AL3X** [comment]
> I suggest making a kits backup for the plugin.

That's what I have in mind

**Comment by realtrollman2319** [comment]
> I'm checking the code, let me see whats happening, if you can, send me your kits.json and your rocket.log here

I can't I lost it. All I have is the backup from my notepad++ which is outdated

**Comment by TH3AL3X** [comment]
Try this version, i added a double check if "kits.json" exists and renamed vote to "votepoll"
[uEssentials.zip](https://github.com/TH3AL3X/uEssentials/files/9774752/uEssentials.zip)

**Comment by TH3AL3X** [comment]
![image](https://user-images.githubusercontent.com/13141042/195551633-9f0c0132-f9a3-40b1-a69b-7f8220b8ab93.png)

**Comment by TH3AL3X** [comment]
![image](https://user-images.githubusercontent.com/13141042/195552578-e3d2c97b-ded1-4fe4-b231-3f026c68da01.png)
I think the error is in this line, it may be a failure of the net framework, because it confuses linux with windows to this double check here
![image](https://user-images.githubusercontent.com/13141042/195552860-4afe8cb0-e98f-4590-a062-4ae8f172859b.png)

**Comment by realtrollman2319** [comment]
My server is on Linux, most servers are, but still make it windows for homemade servers

**Comment by TH3AL3X** [comment]
Try the version that I have given you, if it continues to fail, it is a problem with the bars, I will do it in another way and I will leave it here and try both versions

**Comment by realtrollman2319** [comment]
Kits are clearing but JSON are parsed to what it is, server stopped at loading level 18%.
Possible fix is load and save kits after the level has loaded. Just like "14 kits loaded"

**Comment by TH3AL3X** [comment]
My English is very bad, I need you to explain to me step by step what is happening, if it deletes the kits when loading uEssentials, or if it deletes them when it is in the Level loading phase

**Comment by TH3AL3X** [comment]
[uEssentials Fix.zip](https://github.com/TH3AL3X/uEssentials/files/9774882/uEssentials.Fix.zip)
Try this version too, I have changed some parameters

**Comment by realtrollman2319** [comment]
It deletes while the level haven't loaded

**Comment by TH3AL3X** [comment]
Try the latest version i sent

**Comment by realtrollman2319** [comment]
So when you stop the server before level loaded, it will break the kits.
If you stop server after level loaded, it does not break

**Comment by realtrollman2319** [comment]
Kits still break

**Comment by realtrollman2319** [comment]
Make it so the "kits saved" line should only save at level loaded. The plugin thinks there are no kits, when the level have not loaded. So add a if level loaded, save kits

**Comment by TH3AL3X** [comment]
![image](https://user-images.githubusercontent.com/13141042/195557479-530946be-5724-4222-8cd9-abd20897b7ec.png)
ima change this line

**Comment by realtrollman2319** [comment]
go ahead

**Comment by TH3AL3X** [comment]
[uEssentials.zip](https://github.com/TH3AL3X/uEssentials/files/9775000/uEssentials.zip)

**Comment by TH3AL3X** [comment]
Is it solved?

**Comment by realtrollman2319** [comment]
Yes

**Comment by realtrollman2319** [comment]
Index was outside the bounds of the array.
  at SDG.Unturned.UseableGun.equip () [0x0063a] in <52cae494c9834d89a27dbd4ae8eeae8d>:0 
  at (wrapper dynamic-method) SDG.Unturned.PlayerEquipment.SDG.Unturned.PlayerEquipment.ReceiveEquip_Patch1(SDG.Unturned.PlayerEquipment,byte,byte,byte,System.Guid,byte,byte[],SDG.Unturned.NetId)

**Comment by realtrollman2319** [comment]
The kits get formatted the wrong way

**Comment by realtrollman2319** [comment]
that causes that error
normal
![image](https://user-images.githubusercontent.com/108993392/195596050-e174a653-1ef9-48ab-b498-83805df3142b.png)

new 
![image](https://user-images.githubusercontent.com/108993392/195596207-902a5a54-3076-4b46-ad7b-1107d9deda8c.png)

**Comment by TH3AL3X** [comment]
I will check that and pull a update today, so i'm going to close this ticket

**Comment by realtrollman2319** [comment]
Any updates?

**Comment by realtrollman2319** [comment]
It's been 4 months xD
