### ISSUE TITLE
Problem with maxskills

### ISSUE THREAD

**Issue by ShamHyper** [TH3AL3X/uEssentials#41]
[uEssentials] [ERROR] An error ocurred while executing command: 'maxskills белый'
[uEssentials] [ERROR] System.FormatException: String was not recognized as a valid Boolean.
at System.Boolean.Parse (System.String value) [0x00024] in <695d1cc93cca45069c528c15c9fdd749>:0
at Essentials.Core.Command.CommandArgument.get_ToBool () [0x00006] in <5ec7e941e196448ea3aab2a2fe10806a>:0
at Essentials.Commands.CommandMaxSkills.OnExecute (Essentials.Api.Command.Source.ICommandSource src, Essentials.Api.Command.ICommandArgs args) [0x0003e] in <5ec7e941e196448ea3aab2a2fe10806a>:0
at Essentials.Core.Command.CommandAdapter.Execute (Rocket.API.IRocketPlayer caller, System.String[] args) [0x00115] in <5ec7e941e196448ea3aab2a2fe10806a>:0

**Comment by ShamHyper** [comment]
> /maxskills true USERNAME

The problem occurs when the site with an auto-donation issues via the console by nickname, I checked, the command works crookedly through the console now, always errors. Before the update 3.22.20.0, everything was fine, and it was issued by SteamID or nickname

**Comment by ShamHyper** [comment]
if you manage to fix it, please write about it here, at the moment maxskills only works for itself and in the chat, and not in the console as required

**Comment by TeemoCell** [comment]
Maxskills works for me from console and as player.

**Comment by TH3AL3X** [comment]
> > /maxskills true USERNAME
> 
> The problem occurs when the site with an auto-donation issues via the console by nickname, I checked, the command works crookedly through the console now, always errors. Before the update 3.22.20.0, everything was fine, and it was issued by SteamID or nickname

Are you sure you have the latests rocketmod?

**Comment by ShamHyper** [comment]
> > > /maxskills true USERNAME
> > 
> > 
> > The problem occurs when the site with an auto-donation issues via the console by nickname, I checked, the command works crookedly through the console now, always errors. Before the update 3.22.20.0, everything was fine, and it was issued by SteamID or nickname
> 
> Are you sure you have the latests rocketmod?

Yep

**Comment by TH3AL3X** [comment]
> > > > /maxskills true USERNAME
> > > 
> > > 
> > > The problem occurs when the site with an auto-donation issues via the console by nickname, I checked, the command works crookedly through the console now, always errors. Before the update 3.22.20.0, everything was fine, and it was issued by SteamID or nickname
> > 
> > 
> > Are you sure you have the latests rocketmod?
> 
> Yep

Send me here your rocketlogs
