### ISSUE TITLE
uEssentials >> <color=blue>[uEssentials]</color> This is an announcement

### ISSUE THREAD

**Issue by DarkArtz0** [TH3AL3X/uEssentials#44]
this thing pops up in the console its annoying

**Comment by TH3AL3X** [comment]
Disable it "config.json"

**Comment by DarkArtz0** [comment]
> Disable it "config.json"

which option?

**Comment by TH3AL3X** [comment]
Go to config.json and disable auto announcements

**Comment by DarkArtz0** [comment]
> Go to config.json and disable auto announcements

its already disabled its false

**Comment by DarkArtz0** [comment]
I think have to close and open my server again have a good day
