### ISSUE TITLE
Kits not showing up properly

### ISSUE THREAD

**Issue by DarkArtz0** [TH3AL3X/uEssentials#45]
We cant see all of our kits only 1 im gonna send the file, i cant see any errors.
[message (2).txt](https://github.com/TH3AL3X/uEssentials/files/10478728/message.2.txt)

**Comment by DarkArtz0** [comment]
And the permissions file
[message (3).txt](https://github.com/TH3AL3X/uEssentials/files/10478747/message.3.txt)

**Comment by TH3AL3X** [comment]
I don't know whats going on, it's probably a permission issue, if you can explain better whats going on, and when its happening, like if you have full permissions "admin" you can see all kits?

**Comment by DarkArtz0** [comment]
> I don't know whats going on, it's probably a permission issue, if you can explain better whats going on, and when its happening, like if you have full permissions "admin" you can see all kits?

no i cant see all kits

**Comment by TH3AL3X** [comment]
> > I don't know whats going on, it's probably a permission issue, if you can explain better whats going on, and when its happening, like if you have full permissions "admin" you can see all kits?
> 
> no i cant see all kits

I think its a problem of your permissions and not from the plugin
