### ISSUE TITLE
/ammo & /salvagetime

### ISSUE THREAD

**Issue by Cupbearer0236** [TH3AL3X/uEssentials#47]
You should add a limit to how much ammo you can spawn in with /ammo, to prevent people from crashing the server. Also, doing /salvagetime speeds up your character's speed, instead of only speeding up your salvagetime. I think it should be more like the version from this plugin: https://github.com/ShimmyMySherbet/ShimmysAdminTools

**Comment by TH3AL3X** [comment]
> You should add a limit to how much ammo you can spawn in with /ammo, to prevent people from crashing the server. Also, doing /salvagetime speeds up your character's speed, instead of only speeding up your salvagetime. I think it should be more like the version from this plugin: https://github.com/ShimmyMySherbet/ShimmysAdminTools

Sorry for the late, i gotta check that soon....

**Comment by TH3AL3X** [comment]
https://github.com/TH3AL3X/uEssentials/releases/tag/1.3.8.2
