### ISSUE TITLE
Uessentials not loading.

### ISSUE THREAD

**Issue by Planetary-Nebula** [TH3AL3X/uEssentials#49]
[uEssentials] [INFO] Enabling uEssentials...
[uEssentials] [INFO] This is a new version of uEssentials, maintained by Terror
[uEssentials] [INFO] Plugin version: 999.33.40.94 (development)
[uEssentials] [INFO] Recommended Rocket version: 4.X.X.X
[uEssentials] [INFO] Recommended Unturned version: 3.X.X.X
[uEssentials] [INFO] Author: leonardosnt
[uEssentials] [INFO] Wiki: uessentials.github.io
[uEssentials] [ERROR] An error occurred while enabling uEssentials.
[uEssentials] [ERROR] If this error is not related with wrong configuration, please report
[uEssentials] [ERROR] it here https://github.com/TH3AL3X/uEssentials/issues
[uEssentials] [ERROR] Error: System.NullReferenceException: Object reference not set to an instance of an object
  at Essentials.Core.Event.EventManager.RegisterAll (System.Object instance) [0x00099] in <5ec7e941e196448ea3aab2a2fe10806a>:0
  
  I get this error when trying to launch my server, I require uEssentials for my Greylisting system so I cannot launch my server again for the public if this issue remains.

**Comment by TH3AL3X** [comment]
> [uEssentials] [INFO] Enabling uEssentials... [uEssentials] [INFO] This is a new version of uEssentials, maintained by Terror [uEssentials] [INFO] Plugin version: 999.33.40.94 (development) [uEssentials] [INFO] Recommended Rocket version: 4.X.X.X [uEssentials] [INFO] Recommended Unturned version: 3.X.X.X [uEssentials] [INFO] Author: leonardosnt [uEssentials] [INFO] Wiki: uessentials.github.io [uEssentials] [ERROR] An error occurred while enabling uEssentials. [uEssentials] [ERROR] If this error is not related with wrong configuration, please report [uEssentials] [ERROR] it here https://github.com/TH3AL3X/uEssentials/issues [uEssentials] [ERROR] Error: System.NullReferenceException: Object reference not set to an instance of an object at Essentials.Core.Event.EventManager.RegisterAll (System.Object instance) [0x00099] in <5ec7e941e196448ea3aab2a2fe10806a>:0
> 
> I get this error when trying to launch my server, I require uEssentials for my Greylisting system so I cannot launch my server again for the public if this issue remains.

Are you sure, you have the latest version of rocketmod?

**Comment by TH3AL3X** [comment]
Anyways you can try this version
[uEss.zip](https://github.com/TH3AL3X/uEssentials/files/12260510/uEss.zip)
