### ISSUE TITLE
Vehicle blacklist not working

### ISSUE THREAD

**Issue by TheArkian** [TH3AL3X/uEssentials#5]
When going down to `"VehicleBlacklist": []` in config.json and putting some ids in there, you can still spawn the vehicles. Am I doing this wrong or is this a bug?

```"VehicleBlacklist": [
      140,
      109
  ]```
  is what I have now, but ive tried with speech marks too

**Comment by TheArkian** [comment]
Sorry the last part looks bad
```
"VehicleBlacklist": [
      140,
      109
  ],
 ```

**Comment by TheArkian** [comment]
For some reason I thought it wouldnt ignore admins smh

**Comment by TeemoCell** [comment]
Just don't give admins the Cyan name admin. Create a extra group. Never give admins full permission.
