### ISSUE TITLE
`/ammo` command does not spawn in magazines

### ISSUE THREAD

**Issue by G4BE** [TH3AL3X/uEssentials#51]
Prior to the recent update regarding the ammo command, 
(if permitted) players could use the `/ammo` and `/ammo <amount>` commands.

When players used `/ammo` they received one magazine for the gun they were holding.
When players used `/ammo x` they received _x_ magazines for the gun they were holding.

With the recent update this command has broken.
Now when trying to use either of the `/ammo` commands, neither commands work.
<hr/>

Here is the console when I run both the `/ammo` and the `/ammo <amount>` commands.
<image src="https://github-production-user-asset-6210df.s3.amazonaws.com/50008104/273481628-8a63e0ce-9771-41dd-901d-df9d4565f16a.png" title="/ammo command usage from console - shows no error messages">

This is the configuration for uessentials:
<image src="https://github-production-user-asset-6210df.s3.amazonaws.com/50008104/273481744-df611a66-184a-49a8-8808-a7a6b780d512.png" title="config file screenshot">

I have attached the Rocket.log file. 
<i>Please note: some of the errors in that rocket.log file are related to other plugins and are irrelevant to this issue.</i>
[Rocket (1).log](https://github.com/TH3AL3X/uEssentials/files/12842095/Rocket.1.log)

**Comment by TH3AL3X** [comment]
Only /ammo command ?, I will check it today

**Comment by TH3AL3X** [comment]
For some reasons for me its working fine, i will send you my version and let me know if it is working, if not remove Commands.config.xml
[uEss.zip](https://github.com/TH3AL3X/uEssentials/files/12861932/uEss.zip)

**Comment by G4BE** [comment]
I compared the uEssentials you just sent me with the latest release.
I believe the reason you aren't having problems is because your server is still running the 1.3.8.1 and you haven't updated to the latest release yet.

Left: Latest Release         |    Right: uEss.zip
<image src="https://github-production-user-asset-6210df.s3.amazonaws.com/50008104/274113157-2bc35a17-49d1-412c-a77b-f498b344eed6.png">

**Comment by TH3AL3X** [comment]
> I compared the uEssentials you just sent me with the latest release.
> 
> I believe the reason you aren't having problems is because your server is still running the 1.3.8.1 and you haven't updated to the latest release yet.
> 
> 
> 
> Left: Latest Release         |    Right: uEss.zip
> 
> <image src="https://github-production-user-asset-6210df.s3.amazonaws.com/50008104/274113157-2bc35a17-49d1-412c-a77b-f498b344eed6.png">
> 
> 

My server is updated, and I tested it, anyways, don't look at the version of the plugin, because I have different uEssentials, let me know if that version it's working for you

**Comment by G4BE** [comment]
> > I compared the uEssentials you just sent me with the latest release.
> > I believe the reason you aren't having problems is because your server is still running the 1.3.8.1 and you haven't updated to the latest release yet.
> > Left: Latest Release         |    Right: uEss.zip
> > ![](https://github-production-user-asset-6210df.s3.amazonaws.com/50008104/274113157-2bc35a17-49d1-412c-a77b-f498b344eed6.png)
> 
> My server is updated, and I tested it, anyways, don't look at the version of the plugin, because I have different uEssentials, let me know if that version it's working for you

I tested your version. 
The `/ammo` command works correctly however there is no restriction on the amount of ammo that can be spawned in.

**Comment by TH3AL3X** [comment]
> > > I compared the uEssentials you just sent me with the latest release.
> > > I believe the reason you aren't having problems is because your server is still running the 1.3.8.1 and you haven't updated to the latest release yet.
> > > Left: Latest Release         |    Right: uEss.zip
> > > ![](https://github-production-user-asset-6210df.s3.amazonaws.com/50008104/274113157-2bc35a17-49d1-412c-a77b-f498b344eed6.png)
> > 
> > 
> > My server is updated, and I tested it, anyways, don't look at the version of the plugin, because I have different uEssentials, let me know if that version it's working for you
> 
> I tested your version. The `/ammo` command works correctly however there is no restriction on the amount of ammo that can be spawned in.

Nope but i can add it

**Comment by TH3AL3X** [comment]
> > > I compared the uEssentials you just sent me with the latest release.
> > > I believe the reason you aren't having problems is because your server is still running the 1.3.8.1 and you haven't updated to the latest release yet.
> > > Left: Latest Release         |    Right: uEss.zip
> > > ![](https://github-production-user-asset-6210df.s3.amazonaws.com/50008104/274113157-2bc35a17-49d1-412c-a77b-f498b344eed6.png)
> > 
> > 
> > My server is updated, and I tested it, anyways, don't look at the version of the plugin, because I have different uEssentials, let me know if that version it's working for you
> 
> I tested your version. The `/ammo` command works correctly however there is no restriction on the amount of ammo that can be spawned in.

I saw there is a option for that in the config.json called "AmmoCommandSpawnLimit"
