### ISSUE TITLE
Code for the plugin

### ISSUE THREAD

**Issue by MalevichFX** [TH3AL3X/uEssentials#53]
Hello, I have the code for the plugin here, but I can't seem to compile it and upload it to the public don't have any time, and I would like it to be in your plugin, I will be very glad that he sees it in this plugin like this , as I used it for a long time, it contains these 

**commands:**

**/sedit <steamid/nickname> <height>x<width> - Change the size of the player's storage.
/sreturn <steamid/nickname> - Reset the player's storage size to standard.
/s - Open or close the player's storage.**

[MyStorage.txt](https://github.com/TH3AL3X/uEssentials/files/14505542/MyStorage.txt)

Good luck)

**Comment by MalevichFX** [comment]
)

**Comment by TH3AL3X** [comment]
Missing class "ItemStorage"

**Comment by TH3AL3X** [comment]
I gotta close this, no replies
