### ISSUE TITLE
Ammo Bug?

### ISSUE THREAD

**Issue by Emporium8231** [TH3AL3X/uEssentials#58]
When I execute the command `/ammo` it gives me nothing.

![image](https://github.com/TH3AL3X/uEssentials/assets/162950786/0c0268a9-9670-47cd-b118-b24504af7732)

When I execute the command `/ammo 1` it still gives me nothing.

![image](https://github.com/TH3AL3X/uEssentials/assets/162950786/eeb4ecbf-2d98-42ce-9ed2-7c4acea21722)

When I execute the command `/ammo 10` it gives me 1 ammo.

![image](https://github.com/TH3AL3X/uEssentials/assets/162950786/ff9701bb-76ec-4d07-8703-d1c89fe02252)

I'm not sure if I messed up something in the config or what.

**Comment by TH3AL3X** [comment]
Hello, /ammo commands its only when you have a weapon in your hands, when you type /ammo 10, if you have for example 30 bullets in your mag, it will put 10 bullets in your mag, also the /ammo command without argument i think is bugged, i need to check it

**Comment by Emporium8231** [comment]
I thought `/ammo` gives you additional full mags in your inventory? That's how the other ammo plugin worked from what I saw. Also, is it possible to specify what mag you want to use for your gun or is that not possible? Like there is the regular mag for a gun from Nordic, but sometimes people want the extended one instead.

**Comment by TH3AL3X** [comment]
> I thought `/ammo` gives you additional full mags in your inventory? That's how the other ammo plugin worked from what I saw. Also, is it possible to specify what mag you want to use for your gun or is that not possible? Like there is the regular mag for a gun from Nordic, but sometimes people want the extended one instead.

Use /item

**Comment by TH3AL3X** [comment]
Also for the thing you wanted, you first need to put the mag you want to refill, but i can add to /ammo an argument like /ammo "ID OF MAG" "AMOUNT"
