### ISSUE TITLE
Issue still exists after update with Essentials.Core.EssCore.OnVehicleExploded

### ISSUE THREAD

**Issue by joeymisfit** [TH3AL3X/uEssentials#62]
In console it just spams the following when a car gets blown up;

> [20:34:14 ERR][SDG.Unturned] Caught exception invoking OnVehicleExploded(0 (SDG.Unturned.InteractableVehicle)):
> [20:34:14 ERR][SDG.Unturned] Object reference not set to an instance of an object
> [20:34:14 ERR][SDG.Unturned]   at Essentials.Core.EssCore.OnVehicleExploded (SDG.Unturned.InteractableVehicle vehicle) [0x00007] in <13cfc6b7cd8947f88be0d5f616180185>:0 
>   at SDG.Unturned.SystemActionEx.TryInvoke[T] (System.Action`1[T] action, System.String debugName, T obj) [0x00003] in <83c9359590004aa1b37b3b3d0ab468d0>:0

**Comment by TH3AL3X** [comment]
I will check it again, anyways thats only can block the feature of "/vehiclefeatures autorepair on"

**Comment by joeymisfit** [comment]
> I will check it again, anyways thats only can block the feature of "/vehiclefeatures autorepair on"

Thank you, it's so weird how it spams console so much.

**Comment by TH3AL3X** [comment]
https://github.com/TH3AL3X/uEssentials/releases/tag/v1.0.23

**Comment by joeymisfit** [comment]
I noticed the error still exists, do I need to regenerate the configs or is there something still broken?
![chrome_WcKi2Sciub](https://github.com/user-attachments/assets/6e55c915-4824-4a38-96d9-79a95ef8ae94)

**Comment by TH3AL3X** [comment]
I think i need to add more checkers, the error come randomly

> I noticed the error still exists, do I need to regenerate the configs or is there something still broken? ![chrome_WcKi2Sciub](https://private-user-images.githubusercontent.com/20868143/352779095-6e55c915-4824-4a38-96d9-79a95ef8ae94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMDIyMTcsIm5iZiI6MTcyMjIwMTkxNywicGF0aCI6Ii8yMDg2ODE0My8zNTI3NzkwOTUtNmU1NWM5MTUtNDgyNC00YTM4LTk2ZDktNzlhOTVlZjhhZTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDIxMjUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZmUyOTExMTZjODU1NThlN2Q5OWEyOWRkNjc3OThhMDA2OWRjNWQ3NmMwMjNmYmVlYzY1MzQzZDIwZmZlNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GpbTPUj9fSNAWp0xE1Vzij3U_YRb8fgannvkYBclO1M)
