### ISSUE TITLE
Having problem with Kits.json

### ISSUE THREAD

**Issue by Pain260495** [TH3AL3X/uEssentials#63]
[uEssentials] [ERROR] Failed to parse kit configuration (Plugins/uEssentials/kits.json). Invalid JSON!
[uEssentials] [ERROR] Error reading JArray from JsonReader. Path '', line 0, position 0.

[uEssentials] [ERROR] An error ocurred while executing command: 'createkit Starter 86400'
[uEssentials] [ERROR] Error creating 'Newtonsoft.Json.Converters.StringEnumConverter'.

**Comment by Pain260495** [comment]
and the cooldown file is gone too. All of the kit after restart will reset the cooldown

**Comment by Pain260495** [comment]
I'm now using the Original uEssentials Kits.json it worked but the cooldown still reset after server restart.
and the Cooldown file for all of the kit is not there.

**Comment by TH3AL3X** [comment]
> [uEssentials] [ERROR] Failed to parse kit configuration (Plugins/uEssentials/kits.json). Invalid JSON!
> 
> [uEssentials] [ERROR] Error reading JArray from JsonReader. Path '', line 0, position 0.
> 
> 
> 
> [uEssentials] [ERROR] An error ocurred while executing command: 'createkit Starter 86400'
> 
> [uEssentials] [ERROR] Error creating 'Newtonsoft.Json.Converters.StringEnumConverter'.

Just validate your JSON file, is incorrect

**Comment by Pain260495** [comment]
what do i do to fix it?

**Comment by Pain260495** [comment]
i already reinstalled the plugin many time

**Comment by Pain260495** [comment]
so after i reinstalled the plugin. Usually it gonna show that the server has 4 default kits but when i reinstalled it only showed the error with 0 kits.

**Comment by Pain260495** [comment]
i still can't use the kit. it has no cooldown nor being able to create kit

**Comment by TH3AL3X** [comment]
> i still can't use the kit. it has no cooldown nor being able to create kit

You're the only one who is having problems, i don't know what is happening, probably ur kits.json is invalid, or you are not using the commands properly and permissions

**Comment by Pain260495** [comment]
so what do i do to fix this problem?
