### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by Savagebike** [TH3AL3X/uEssentials#65]
I'm unsure if this is something to do with how i am naming them in the translations file but upon attempting to fix the color of the text , no matter what I do it doesn't work ( The Server was restarted each time a change was made ).
![image](https://github.com/user-attachments/assets/d4cbca72-a139-4af4-bcaa-edc2dd29e739)
![image](https://github.com/user-attachments/assets/3b64d36f-6891-49b0-bf65-94fa468ea8ad)
![image](https://github.com/user-attachments/assets/31265f3e-6a42-4a05-a8ef-bc20c9335c3c)
![image](https://github.com/user-attachments/assets/3dbe5480-cbbe-486d-96cb-b1071c92255e)

**Comment by TH3AL3X** [comment]
<color=#>TEXT</color>
And you need to disable the  "OldFormatMessages": false, in your config.json
