### ISSUE TITLE
Last Unturned update broke /checkowner

### ISSUE THREAD

**Issue by WCPistolPete** [TH3AL3X/uEssentials#67]
22.10 22:42:33 [Server] INFO [Group] {WC}PistolPete [{WC}PistolPete]: "/checkowner"
22.10 22:42:33 [Server] INFO An error occured while executing checkowner []: System.TypeLoadException: Could not resolve type with token 01000032 from typeref (expected class 'SDG.Unturned.InteractableDoorHinge' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null')
22.10 22:42:33 [Server] INFO at Rocket.Core.Commands.RocketCommandManager+RegisteredRocketCommand.Execute (Rocket.API.IRocketPlayer caller, System.String[] command) [0x00000] in <59a13feb721848c8b0cd173f6d0e820b>:0
22.10 22:42:33 [Server] INFO at Rocket.Core.Commands.RocketCommandManager.Execute (Rocket.API.IRocketPlayer player, System.String command) [0x00176] in <59a13feb721848c8b0cd173f6d0e820b>:0

**Comment by TH3AL3X** [comment]
I'm checking it, and it's working fine, are you sure you have the latest RocketMod?
![image](https://github.com/user-attachments/assets/d13a8fcf-a822-43e1-8a22-8d451ebbcf06)

**Comment by TH3AL3X** [comment]
Fixed https://github.com/TH3AL3X/uEssentials/releases/tag/v1.0.27
