### ISSUE TITLE
/checkowner and /vf all on broken

### ISSUE THREAD

**Issue by WCPistolPete** [TH3AL3X/uEssentials#68]
If you're still working with uEssentials, today's Unturned update broke /checkowner. No response is returned.

The last vehicle update broke /vf all on. One must be in a vehicle to initiate a repair. Once a person exits, the command is lost and must be retyped after re-entering.

Thanks for your help.

**Comment by TH3AL3X** [comment]
Fixed https://github.com/TH3AL3X/uEssentials/releases/tag/v1.0.27
