### ISSUE TITLE
pls fix this error

### ISSUE THREAD

**Issue by dannythehacker** [TH3AL3X/uEssentials#9]
[uEssentials] [ERROR] Failed to load 'config.json'.
[uEssentials] [ERROR] Error converting value "Automatic message" to type 'Essentials.Misc.Message'. Path 'AutoAnnouncer.Messages[0]', line 69, position 25.
[uEssentials] [ERROR] Using default...

**Comment by TeemoCell** [comment]
Wrong configured 'config.json' file. Not a plugin problem.

**Comment by TH3AL3X** [comment]
Yeah, you need to remove your old config.json, due this uEssentials have new stuff...
